
# ------TRAINING PARAMETERS----- #
NUM_EPOCHS: 30
# number of proteins
BATCH_SIZE: 4
NUMBER_RESIDUES_PER_BATCH: 4

LEARNING_RATE: 0.00002

# Training scheme params
discard_intermediates_in_testing: False
balance_classes: False
weight_loss: False
weight_globally: False
oversample: False
undersample: False
constant_size_balanced_sets: False
continue_previous_training: False

# can be edited to automate
train_on_intermediates: False
fold: 4
# ----------------------------- #

# ------- LIGSITE INPUT PARAMETERS ---- #
featurization_method: 'nearby-pv-procedure'
min_rank: 7
window: 40
stride: 1
pos_thresh: 116
neg_thresh: 60
# ----END LIGSITE INPUT PARAMETERS ---- #

# ------- GVP INPUT PARAMETERS ---- #
DROPOUT_RATE: 0.1
HIDDEN_DIM: 100
NUM_LAYERS: 4
# -----END GVP INPUT PARAMETERS ---- #

xtal_validation_path: '/project/bowmanlab/borowsky.jonathan/FAST-cs/protein-sets/new_pockets/labels/new_pocket_labels_validation_all1.npy'
base_path: '/project/bowmanlab/ameller/gvp/task1-final-folds-window-40-nearby-pv-procedure'
