# ------TRAINING PARAMETERS----- #
NUM_EPOCHS: 20
# number of proteins
BATCH_SIZE: 1
residue_batches: True
NUMBER_RESIDUES_PER_BATCH: 4

LEARNING_RATE: 0.00002

# Training scheme params
continue_previous_training: False

# can be edited to automate
use_tensors: True
# ----------------------------- #

# ------- LIGSITE INPUT PARAMETERS ---- #
feat_type: max
stride: 25
window: 40
cutoff: 0.3
# ----END LIGSITE INPUT PARAMETERS ---- #

# ------- GVP INPUT PARAMETERS ---- #
DROPOUT_RATE: 0.1
HIDDEN_DIM: 100
NUM_LAYERS: 4
# -----END GVP INPUT PARAMETERS ---- #

xtal_validation_path: '/project/bowmanlab/borowsky.jonathan/FAST-cs/protein-sets/new_pockets/labels/new_pocket_labels_validation_all1.npy'
xtal_test_path: '/project/bowmanlab/borowsky.jonathan/FAST-cs/protein-sets/new_pockets/labels/new_pocket_labels_test_all1.npy'
base_path: '/project/bowmanlab/ameller/gvp/task2'
