# ------TRAINING PARAMETERS----- #
NUM_EPOCHS: 20
# number of proteins
BATCH_SIZE: 4
residue_batches: True
NUMBER_RESIDUES_PER_BATCH: 4

LEARNING_RATE: 0.00002

# Training scheme params
balance_classes: True
weight_loss: False
weight_globally: False
oversample: False
undersample: False
constant_size_balanced_sets: True
NUMBER_RESIDUES_PER_DRAW: 640

continue_previous_training: False
# ----------------------------- #

# ------- LIGSITE INPUT PARAMETERS ---- #
stride: 10
# ----END LIGSITE INPUT PARAMETERS ---- #
use_tensors: False

# ------- GVP INPUT PARAMETERS ---- #
DROPOUT_RATE: 0.1
HIDDEN_DIM: 100
NUM_LAYERS: 4
# -----END GVP INPUT PARAMETERS ---- #

xtal_validation_path: '/project/bowmanlab/borowsky.jonathan/FAST-cs/protein-sets/new_pockets/labels/new_pocket_labels_validation_all1.npy'
xtal_test_path: '/project/bowmanlab/borowsky.jonathan/FAST-cs/protein-sets/new_pockets/labels/new_pocket_labels_test_all1.npy'
base_path: '/project/bowmanlab/ameller/gvp/task2'
